FROM node:6.10.3

ENV INSROOT /opt/app
ENV APPUSER dh
ENV APPDIR ${INSROOT}/${APPUSER}

WORKDIR ${APPDIR}

RUN mkdir -p ${APPDIR}/lib \
 && mkdir -p ${APPDIR}/tests \
 && mkdir -p ${APPDIR}/etc \
 && mkdir -p ${APPDIR}/log \
 && useradd -d ${APPDIR} ${APPUSER}

COPY *.js ${APPDIR}/
COPY *.json ${APPDIR}/
COPY *.txt ${APPDIR}/
COPY *.yaml ${APPDIR}/
COPY ./lib/ ${APPDIR}/lib/
COPY ./tests/ ${APPDIR}/tests/
COPY ./etc/ ${APPDIR}/etc/

RUN npm install \
 && chown -R ${APPUSER}:${APPUSER} ${APPDIR} \
 && chmod 777 ${APPDIR}/lib \
 && chmod 777 ${APPDIR}/tests \
 && chmod 777 ${APPDIR}/log \
 && chmod 777 ${APPDIR}/etc \
 && pwd \
 && ls -laR -Inode_modules

USER ${APPUSER}
VOLUME ${APPDIR}/log
EXPOSE 8443
ENTRYPOINT ["/usr/local/bin/npm", "test"]
# ENTRYPOINT ["/usr/local/bin/npm", "run", "test-only"]
